version = 0.1

[default.deploy.parameters]
stack_name = "daily-news-service-dev"
s3_prefix = "daily-news-service"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=dev LogLevel=debug UseMockLLM=true"

[prod.deploy.parameters]
stack_name = "daily-news-service-prod"
s3_prefix = "daily-news-service"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=prod"
